#!/bin/bash

### PHP version parameter
php_version=$1

## GET CURRENT PHP VERSION
PHPVersion=$(php -r "echo PHP_VERSION;");
current_php_version=${PHPVersion:0:3};

if [ "$(whoami)" != 'root' ]; then
	echo $"You have no permission to run $0 as non-root user. Use sudo"
	exit 1;
fi

disable_php_cmd="a2dismod php$current_php_version"
enable_php_cmd="a2enmod php$php_version"

create_symlink_php="ln -sfn /usr/bin/php$php_version /etc/alternatives/php";

eval $disable_php_cmd
eval $enable_php_cmd

echo -e $"Creating symlink...\n"
eval $create_symlink_php

/etc/init.d/apache2 reload

echo -e $"Complete!\nYou just changed to PHP $php_version."
exit 0;